
print('               ┌----------------┐'               )
print('               |     Asmund     |'               )
print('               └----------------┘'               )
print('┌----------------------------------------------┐')
print('|           Your name is Harvardr              |')
print('| You are a leader of a great army in the town |')
print('| of Asmund. You are widely known and praised  |')
print('| by many. You are a master in sword fighting. |')
print('| That it will have to come into play very     |')
print('| soon. There are dark forces growing around   |')
print('| the town of Asmund. Bandits filled with envy |')
print("| of the great city and it's riches, evil      |")
print('| creatures that are out for blood, dark mages |')
print('| that want the secrets hidden deep inside the |')
print('| walls of the town, but none of these compare |')
print('| to the true enemy, Andulf and the Murkrfoss. |')
print('| An old town that was cursed by the gods to   |')
print('| be turned into wolf like creatures that are  |')
print('| full of hatred for the human race. Your job  |')
print('|    is to protect your town at all costs.     |')
print('|                   Good Luck                  |')
print('└----------------------------------------------┘')

